name: Continuous Integration Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  test:
    name: 'Run unit tests'
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'

    - name: 'Install Dependencies'
      run: npm install
    
    - name: 'Run Unitary Tests'
      run: npm run test
    
    - name: 'Run complexity'
      run: npm run lint
      
    - name: 'Run coverage'
      run: npm run test:coverage           